### ISSUE TITLE
setup entry with only name can default to package

### ISSUE THREAD

**Issue by yo3jones** [yo3jones/yconfig#30]
can expand

```yaml
setup:
  - name: neofetch
```

or 

```yaml
setup:
  - neofetch
```

to

```yaml
setup:
  - name: neofetch
    type: package
    packages: neofetch
```
