### ISSUE TITLE
allow for different setup types in values

### ISSUE THREAD

**Issue by yo3jones** [yo3jones/yconfig#31]
example

```yaml
setup:
  - name: foo
    values:
      - type: package
        os: linux
        packages: somePackage
      - type: script
        os: darwin
        script: some script
```

or even more simple

```yaml
setup:
  - name: foo
    values:
      - os: linux
        packages: somePackage
      - os: darwin
        script: some script
```
