### ISSUE TITLE
add setup continue on error flag

### ISSUE THREAD

**Issue by yo3jones** [yo3jones/yconfig#34]
```yaml
setup:
  - name: foo
    continueOnError: true
    script: echo foo
```

also 

```yaml
setup:
  - name: foo
    type: script
    values:
      - continueOnError: true
        tags: foo
        script: echo foo
      - tags: bar
        script: echo bar
```
