### ISSUE TITLE
add setup retry functionality

### ISSUE THREAD

**Issue by yo3jones** [yo3jones/yconfig#35]
```yaml
setup:
  - name: foo
    retry: 2
    script: echo foo
```

or 

```yaml
setup:
  - name: foo
    retry: 
      count: 0
      behavior: IN_PLACE # possible values: IN_PLACE, AT_END (default IN_PLACE)
    script: echo foo
```

also in values 

```yaml
setup:
  - name: foo
    type: script
    values:
      - retry: 3
```
