### ISSUE TITLE
setup entries should not run if all runtime tags don't match

### ISSUE THREAD

**Issue by yo3jones** [yo3jones/yconfig#36]
```yaml
setup:
  - name: foo
    tags:
      - one
      - two
    script: echo foo
  - name: bar
    tags:
      - one
    script: echo bar
```

```
yconfig setup --tag one --tag two
```

should only run `foo`, currently runs both `foo` and `bar`
