### ISSUE TITLE
add git type to setup

### ISSUE THREAD

**Issue by yo3jones** [yo3jones/yconfig#40]
```yaml
setup:
  - name: foo
    type: git # optional
    repo: https://github.com/yo3jones/yconfig.git # or can do short hand like yo3jones/yconfig
    dest: ~/dev # optional
```

or

 ```yaml
setup:
  - name: foo
    values:
        - type: git # optional
          repo: https://github.com/yo3jones/yconfig.git # or can do short hand like yo3jones/yconfig
          dest: ~/dev # optional
```
