### ISSUE TITLE
fix error view when not continueOnError for setup

### ISSUE THREAD

**Issue by yo3jones** [yo3jones/yconfig#56]
```yaml
setup:
  - name: foo
    continueOnError: false
    script: |-
      echo foo \
      && sleep 1 \
      && aksdjf
  - name: bar
    script: |-
      echo foo \
      && sleep 1
```
